### ISSUE TITLE
Changing turnOverRate and netDiversification does not affect BirthHybridizationModel

### ISSUE THREAD

**Issue by Anaphory** [zhangchicool/speciesnetwork#7]
As far as I can see, the code that sets ν and λ from the input parameters
https://github.com/zhangchicool/speciesnetwork/blob/a330f4ab960b0ddd6c7451b9c52095d787c65911/src/speciesnetwork/BirthHybridizationModel.java#L44-L55
is exectuted only at initialization, which means that ν and λ are fixed througout an MCMC run. Setting priors on them would therefore not have any influence on the sampling.

**Comment by zhangchicool** [comment]
thanks for the report. this is now fixed in a8e47db56f867d51604fccac61d4f9e907651564
